name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 20 * * 6'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pages: write
      security-events: write
      actions: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # ----------------------------
      # Ajout : génération du badge
      # ----------------------------

      - name: Run Trivy vulnerability scanner (JSON)
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'json'
          output: 'trivy.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Create badge.json
        run: |
          vulns=$(jq '[.Results[].Vulnerabilities[]?] | length' trivy.json)
          crit=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy.json)
          high=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy.json)

          if [ "$vulns" -eq 0 ]; then
            bg_color="#38b000"
            txt_color="#FFF"
            message="0 vulns"
          elif [ "$crit" -gt 0 ]; then
            bg_color="#F00"
            txt_color="#FFF"
            message="${crit} critical"
          elif [ "$high" -gt 0 ]; then
            bg_color="#ff6d00"
            txt_color="#FFF"
            message="${high} high"
          else
            bg_color="#FFFF3F"
            txt_color="#000"
            message="${vulns} vulns"
          fi

          mkdir -p public
          # cat > public/badge.json <<EOF
          # {
          #   "schemaVersion": 1,
          #   "label": "Trivy",
          #   "message": "$message",
          #   "color": "$color"
          # }
          # EOF
          cat > public/trivy.svg <<EOF
            <svg xmlns="http://www.w3.org/2000/svg" width="120" height="20" role="img" aria-label="Trivy: $message">
            <title>Trivy: $message</title>
            <linearGradient id="s" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <rect rx="3" width="120" height="20" fill="#555"/>
            <rect rx="3" x="60" width="60" height="20" fill="$bg_color"/>
            <path fill="$bg_color" d="M60 0h4v20h-4z"/>
            <rect rx="3" width="120" height="20" fill="url(#s)"/>
            <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
              <text x="30" y="15" fill="#010101" fill-opacity=".3">Trivy</text>
              <text x="30" y="14">Trivy</text>
              <text x="90" y="15" fill="#010101" fill-opacity=".3">$message</text>
              <text x="90" y="14" fill="$txt_color">$message</text>
            </g>
          </svg>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages